/**
 * NewsLabs NLP Service
 * ────────────────────
 * Pure-TypeScript inference engine for:
 *   1. Topic classification  (TF-IDF + Logistic Regression loaded from JSON)
 *   2. Sentiment analysis    (VADER-style lexicon)
 *   3. Opinion vs Fact       (heuristic signals)
 *   4. Reliability scoring   (composite signals)
 *
 * The model artifact (nlp_model.json) is generated by train_nlp.py.
 * If it is missing the service falls back to keyword heuristics.
 */

import fs from 'fs';
import path from 'path';

// ── Types ──────────────────────────────────────────────────────────────────────

export type PrimaryCategory =
    | 'Technology' | 'Business & Finance' | 'World Affairs'
    | 'Science & Space' | 'Health' | 'Sports' | 'Entertainment'
    | 'Climate & Environment' | 'General';

export type Sentiment = 'Positive' | 'Neutral' | 'Negative';
export type ArticleType = 'Opinion' | 'Factual';
export type ReliabilityTier = 'High' | 'Medium' | 'Low';

export interface ClassificationResult {
    primary: PrimaryCategory;
    confidence: number;       // 0–1
    secondaryTags: string[];
    classificationSignals?: string[];
}

export interface SentimentResult {
    sentiment: Sentiment;
    score: number;            // –1 to +1
    signals?: string[];       // words that triggered the result
}

export interface OpinionResult {
    type: ArticleType;
    confidence: number;       // 0–1
    signals?: string[];       // words/patterns that triggered the result
}

export interface ReliabilityResult {
    score: number;            // 0–100
    tier: ReliabilityTier;
    signals: string[];
}

interface ModelArtifact {
    vocab: Record<string, number>;
    idf: number[];
    coef: number[][];
    intercept: number[];
    classes: string[];
    sublinear_tf: boolean;
}

// ── Constants ──────────────────────────────────────────────────────────────────

const MODEL_PATH = path.resolve(process.cwd(), 'src/data/nlp_model.json');
const META_PATH  = path.resolve(process.cwd(), 'src/data/nlp_meta.json');

const FINAL_CATEGORIES: PrimaryCategory[] = [
    'Technology', 'Business & Finance', 'World Affairs', 'Science & Space',
    'Health', 'Sports', 'Entertainment', 'Climate & Environment', 'General',
];

// Secondary tags derived from keyword heuristics (not the primary classifier)
const SECONDARY_KEYWORD_MAP: Record<string, string[]> = {
    'AI & ML':    ['ai', 'artificial intelligence', 'machine learning', 'llm', 'gpt', 'openai', 'anthropic', 'gemini', 'claude', 'neural', 'diffusion', 'chatbot', 'nlp'],
    'Security':   ['hack', 'breach', 'vulnerability', 'malware', 'ransomware', 'cyber', 'phishing', 'zero-day', 'ddos', 'exploit'],
    'Startups':   ['startup', 'founder', 'venture capital', 'seed round', 'series a', 'series b', 'unicorn', 'ipo', 'accelerator'],
    'Crypto':     ['bitcoin', 'ethereum', 'blockchain', 'crypto', 'defi', 'nft', 'token', 'web3', 'solana', 'coinbase'],
    'DevOps':     ['docker', 'kubernetes', 'k8s', 'devops', 'ci/cd', 'terraform', 'serverless', 'microservices'],
    'Web Dev':    ['react', 'nextjs', 'javascript', 'typescript', 'frontend', 'backend', 'api', 'graphql', 'node'],
    'Space':      ['nasa', 'spacex', 'rocket', 'satellite', 'mars', 'astronaut', 'orbital', 'isro', 'lunar'],
    'India':      ['india', 'indian', 'modi', 'delhi', 'mumbai', 'bengaluru', 'rupee', 'bcci', 'bollywood'],
};

// ── India-specific entity detection ──────────────────────────────────────────
// The training dataset is Western-focused; Indian political entities need
// post-processing heuristics to avoid mis-classification.

const INDIA_POLITICAL_ENTITIES = [
    'bjp', 'bharatiya janata', 'indian national congress', 'aam aadmi party', 'aap ',
    'trinamool', 'tmc ', 'shiv sena', 'shivsena', 'samajwadi party', 'bsp ', 'bahujan',
    'ncp ', 'rashtriya', 'jdu ', 'rjd ', 'lok sabha', 'rajya sabha', 'vidhan sabha',
    'modi ', 'narendra modi', 'pm modi', 'rahul gandhi', 'sonia gandhi', 'priyanka gandhi',
    'amit shah', 'yogi adityanath', 'mamata banerjee', 'arvind kejriwal', 'nitish kumar',
    'lalu prasad', 'election commission of india', 'india election', 'india parliament',
];

const INDIA_GEO_CULTURE = [
    'india', 'indian', 'new delhi', 'mumbai', 'bengaluru', 'bangalore', 'chennai',
    'kolkata', 'hyderabad', 'pune', 'ahmedabad', 'uttar pradesh', 'maharashtra',
    'rupee', 'rbi', 'sensex', 'nifty', 'sebi', 'niti aayog',
    'bollywood', 'tollywood', 'bcci', 'ipl', 'team india',
    'tata group', 'reliance industries', 'infosys', 'wipro', 'tcs',
];

const INDIA_CORRECT_TARGETS: PrimaryCategory[] = [
    'World Affairs', 'Business & Finance', 'Health', 'Sports', 'Entertainment',
    'Technology', 'Science & Space', 'Climate & Environment',
];

function applyIndiaOverride(
    primary: PrimaryCategory,
    text: string,
    secondaryTags: string[]
): { primary: PrimaryCategory; secondaryTags: string[] } {
    const lower = text.toLowerCase();

    let hasIndiaPolitical = false;
    for (const entity of INDIA_POLITICAL_ENTITIES) {
        if (lower.includes(entity)) { hasIndiaPolitical = true; break; }
    }

    let indiaGeoCount = 0;
    for (const term of INDIA_GEO_CULTURE) {
        if (lower.includes(term)) indiaGeoCount++;
    }

    const hasStrongIndia = hasIndiaPolitical || indiaGeoCount >= 2;
    if (!hasStrongIndia) return { primary, secondaryTags };

    const tags = secondaryTags.includes('India') ? secondaryTags : ['India', ...secondaryTags].slice(0, 3);

    // Override only clearly wrong categories for India political news
    if (hasIndiaPolitical && !INDIA_CORRECT_TARGETS.includes(primary)) {
        return { primary: 'World Affairs', secondaryTags: tags };
    }
    if (hasIndiaPolitical && primary === 'General') {
        return { primary: 'World Affairs', secondaryTags: tags };
    }

    return { primary, secondaryTags: tags };
}

// ── Trusted source list ───────────────────────────────────────────────────────
const TRUSTED_SOURCES: Record<string, number> = {
    'bbc': 25, 'reuters': 25, 'ap news': 25, 'associated press': 25,
    'nyt': 20, 'new york times': 20, 'washington post': 20,
    'guardian': 18, 'bloomberg': 18, 'financial times': 18,
    'nature': 22, 'science': 22, 'sciencedaily': 20,
    'cnbc': 15, 'cnn': 12, 'forbes': 12, 'wired': 15, 'the verge': 14,
    'techcrunch': 13, 'ars technica': 16,
    'espn': 15, 'hindu': 16, 'hindustan times': 14, 'times of india': 14,
    'ndtv': 12, 'indian express': 14, 'firstpost': 11,
};

// Clickbait signals
const CLICKBAIT_PATTERNS = [
    /you won'?t believe/i, /this will (shock|amaze|blow)/i,
    /\b(shocking|mindblowing|unbelievable|incredible|insane)\b/i,
    /\bclick(bait)?\b/i, /\d+ (reasons|things|ways|secrets|tricks)\b/i,
    /what happens next/i, /doctors hate/i, /one weird trick/i,
];

// Opinion signals
const OPINION_WORDS = [
    'should', 'must', 'need to', 'ought to', 'believe', 'think', 'feel',
    'argue', 'claim', 'opinion', 'view', 'perspective', 'i think', 'we must',
    'in my view', 'it is time', 'we should', 'we need', 'wake up',
    'dangerous', 'wrong', 'right', 'terrible', 'wonderful', 'outrageous',
    'disgrace', 'shameful', 'brilliant', 'absurd', 'ridiculous',
];

// Factual signals
const FACTUAL_SIGNALS = [
    /\b(said|says|stated|confirmed|announced|reported|according to)\b/i,
    /\b\d+(\.\d+)?(%|percent|million|billion|trillion|thousand)\b/i,
    /\b(monday|tuesday|wednesday|thursday|friday|saturday|sunday)\b/i,
    /\b(january|february|march|april|may|june|july|august|september|october|november|december)\b/i,
    /"\w[^"]{5,}"/,       // quoted speech
    /\b[A-Z][a-z]+ [A-Z][a-z]+\b/,   // proper nouns (NER approximation)
];

// Sentiment lexicon (curated, balanced)
const POSITIVE_WORDS = new Set([
    'good', 'great', 'excellent', 'positive', 'success', 'win', 'won', 'victory',
    'growth', 'improve', 'improvement', 'record', 'breakthrough', 'innovation',
    'benefit', 'gain', 'rise', 'boost', 'surge', 'thrive', 'profit', 'advance',
    'launch', 'award', 'celebrate', 'recover', 'solution', 'hope', 'progress',
    'agreement', 'deal', 'partnership', 'approved', 'support', 'efficient',
    'effective', 'lead', 'leading', 'best', 'top', 'strong', 'healthy',
    'safe', 'secure', 'peace', 'save', 'rescue', 'discover', 'expand',
]);

const NEGATIVE_WORDS = new Set([
    'bad', 'poor', 'fail', 'failure', 'loss', 'lose', 'lost', 'decline',
    'drop', 'fall', 'crash', 'crisis', 'disaster', 'concern', 'worry', 'fear',
    'threat', 'risk', 'danger', 'attack', 'war', 'conflict', 'dead', 'death',
    'kill', 'hurt', 'injury', 'disease', 'outbreak', 'ban', 'block', 'cut',
    'layoff', 'fired', 'sue', 'sued', 'scandal', 'fraud', 'corruption',
    'breach', 'hack', 'leak', 'crash', 'collapse', 'bankrupt', 'deficit',
    'inflation', 'recession', 'violence', 'protest', 'riot', 'resign',
]);

const NEGATION_WORDS = new Set(['not', 'no', 'never', 'neither', 'nor', "n't", 'without', 'fails', 'unable']);

// ── Math helpers ───────────────────────────────────────────────────────────────

function softmax(logits: number[]): number[] {
    const max = Math.max(...logits);
    const exps = logits.map(x => Math.exp(x - max));
    const sum = exps.reduce((a, b) => a + b, 0);
    return exps.map(e => e / sum);
}

function tokenize(text: string): string[] {
    return text.toLowerCase()
        .replace(/[^a-z0-9\s\-]/g, ' ')
        .split(/\s+/)
        .filter(t => t.length > 1);
}

// ── TF-IDF + LogReg inference ──────────────────────────────────────────────────

function tfidfTransform(tokens: string[], model: ModelArtifact): number[] {
    const numFeatures = model.idf.length;
    const tf: number[] = new Array(numFeatures).fill(0);
    const vocab = model.vocab;

    // Count term frequencies (bigrams too)
    for (let i = 0; i < tokens.length; i++) {
        const t1 = tokens[i];
        if (vocab[t1] !== undefined) tf[vocab[t1]] += 1;
        if (i + 1 < tokens.length) {
            const bigram = `${t1} ${tokens[i + 1]}`;
            if (vocab[bigram] !== undefined) tf[vocab[bigram]] += 1;
        }
    }

    // Apply sublinear TF + IDF
    const vec: number[] = new Array(numFeatures).fill(0);
    let norm = 0;
    for (let i = 0; i < numFeatures; i++) {
        if (tf[i] > 0) {
            const tfVal = model.sublinear_tf ? (1 + Math.log(tf[i])) : tf[i];
            vec[i] = tfVal * model.idf[i];
            norm += vec[i] * vec[i];
        }
    }

    // L2 normalise
    if (norm > 0) {
        const normFactor = 1 / Math.sqrt(norm);
        for (let i = 0; i < numFeatures; i++) vec[i] *= normFactor;
    }

    return vec;
}

function logregPredict(vec: number[], model: ModelArtifact): { label: string; confidence: number; topFeatures: string[] } {
    const logits = model.coef.map((row, c) => {
        let sum = model.intercept[c];
        for (let i = 0; i < vec.length; i++) {
            if (vec[i] !== 0) sum += row[i] * vec[i];
        }
        return sum;
    });

    const probs = softmax(logits);
    let bestIdx = 0;
    for (let i = 1; i < probs.length; i++) {
        if (probs[i] > probs[bestIdx]) bestIdx = i;
    }

    // Extract top features
    const contributions = [];
    const row = model.coef[bestIdx];
    for (let i = 0; i < vec.length; i++) {
        if (vec[i] !== 0) {
            contributions.push({ index: i, weight: row[i] * vec[i] });
        }
    }
    contributions.sort((a, b) => b.weight - a.weight);
    
    // Invert vocab lazily if needed to map back
    const topIndices = contributions.slice(0, 3).map(c => c.index);
    const topFeatures = [];
    for (const [word, index] of Object.entries(model.vocab)) {
        if (topIndices.includes(index)) {
            topFeatures.push(word);
        }
    }

    return {
        label: model.classes[bestIdx],
        confidence: probs[bestIdx],
        topFeatures,
    };
}

// ── Keyword fallback classifier ────────────────────────────────────────────────

const KEYWORD_CATEGORY_MAP: Record<string, string[]> = {
    'Technology': ['tech', 'software', 'app', 'digital', 'computer', 'internet', 'online', 'data', 'cloud', 'chip', 'semiconductor', 'microsoft', 'apple', 'google', 'meta', 'amazon'],
    'Science & Space': ['science', 'research', 'study', 'physics', 'space', 'nasa', 'planet', 'biology', 'quantum', 'experiment', 'discovery', 'molecule'],
    'Business & Finance': ['business', 'economy', 'stock', 'market', 'bank', 'finance', 'trade', 'revenue', 'profit', 'gdp', 'inflation', 'investment', 'merger', 'acquisition', 'ceo'],
    'World Affairs': ['politics', 'government', 'war', 'conflict', 'election', 'president', 'minister', 'diplomacy', 'military', 'nato', 'un ', 'sanctions', 'treaty', 'parliament'],
    'Health': ['health', 'medical', 'hospital', 'doctor', 'disease', 'vaccine', 'treatment', 'cancer', 'covid', 'fda', 'clinical', 'wellness', 'nutrition'],
    'Sports': ['sports', 'game', 'match', 'player', 'team', 'championship', 'tournament', 'nba', 'nfl', 'cricket', 'football', 'soccer', 'tennis', 'olympics'],
    'Entertainment': ['movie', 'film', 'music', 'actor', 'netflix', 'streaming', 'celebrity', 'oscar', 'grammy', 'gaming', 'television', 'show', 'album'],
    'Climate & Environment': ['climate', 'carbon', 'renewable', 'solar', 'emissions', 'environment', 'green', 'wildfire', 'flood', 'drought', 'pollution'],
};

function keywordFallback(text: string): { primary: PrimaryCategory; confidence: number } {
    const lower = text.toLowerCase();
    let best: PrimaryCategory = 'General';
    let bestScore = 0;
    for (const [cat, words] of Object.entries(KEYWORD_CATEGORY_MAP)) {
        const score = words.filter(w => lower.includes(w)).length;
        if (score > bestScore) { bestScore = score; best = cat as PrimaryCategory; }
    }
    return { primary: best, confidence: bestScore > 0 ? Math.min(0.5, bestScore * 0.12) : 0.1 };
}

// ── Secondary tag extraction ───────────────────────────────────────────────────

function extractSecondaryTags(text: string, primary: string): string[] {
    const lower = text.toLowerCase();
    const tokens = new Set(lower.split(/\s+/).map(t => t.replace(/[^a-z0-9]/g, '')));
    const tags: string[] = [];

    for (const [tag, words] of Object.entries(SECONDARY_KEYWORD_MAP)) {
        const matched = words.some(w => {
            // Short words (≤3 chars) need exact token match to avoid substring false positives
            if (w.length <= 3) return tokens.has(w.replace(/[^a-z0-9]/g, ''));
            return lower.includes(w);
        });
        if (matched) tags.push(tag);
    }
    // Don't echo the primary as a secondary tag
    return tags.filter(t => t !== primary).slice(0, 3);
}

// ── Main NLP Service class ─────────────────────────────────────────────────────

class NlpService {
    private model: ModelArtifact | null = null;
    private status: 'ready' | 'missing' | 'loading' = 'loading';
    private meta: Record<string, any> = {};

    constructor() {
        this.loadModel();
    }

    private loadModel() {
        try {
            if (fs.existsSync(MODEL_PATH)) {
                const raw = fs.readFileSync(MODEL_PATH, 'utf-8');
                this.model = JSON.parse(raw) as ModelArtifact;
                this.status = 'ready';
                if (fs.existsSync(META_PATH)) {
                    this.meta = JSON.parse(fs.readFileSync(META_PATH, 'utf-8'));
                }
                console.log(`[NLP] Classifier ready. Categories: ${this.model.classes.join(', ')}`);
                if (this.meta.accuracy) {
                    console.log(`[NLP] Model accuracy: ${(this.meta.accuracy * 100).toFixed(1)}%  (trained ${this.meta.trainedAt?.slice(0, 10) || 'unknown'})`);
                }
            } else {
                this.status = 'missing';
                console.warn('[NLP] nlp_model.json not found — falling back to keyword classifier. Run train_nlp.py to generate it.');
            }
        } catch (err) {
            this.status = 'missing';
            console.error('[NLP] Failed to load model:', err);
        }
    }

    getStatus() {
        return {
            status: this.status,
            accuracy: this.meta.accuracy ?? null,
            trainedAt: this.meta.trainedAt ?? null,
            categories: this.meta.categories ?? FINAL_CATEGORIES,
        };
    }

    // ── 1. Topic classification ──────────────────────────────────────────

    classifyArticle(title: string, content?: string, source?: string): ClassificationResult {
        const text = [title, content].filter(Boolean).join(' ');
        const tokens = tokenize(text);

        let primary: PrimaryCategory;
        let confidence: number;
        let classificationSignals: string[] = [];

        if (this.model && this.status === 'ready' && tokens.length > 0) {
            const vec = tfidfTransform(tokens, this.model);
            const pred = logregPredict(vec, this.model);
            primary = (FINAL_CATEGORIES.includes(pred.label as PrimaryCategory) ? pred.label : 'General') as PrimaryCategory;
            confidence = pred.confidence;
            classificationSignals = pred.topFeatures;

            // Boost confidence with source bias
            if (source && confidence < 0.85) {
                const src = source.toLowerCase();
                if ((src.includes('sciencedaily') || src.includes('nature') || src.includes('science')) && primary !== 'Science & Space') {
                    // Let the model stand, but note override possibility
                }
            }
        } else {
            // Keyword fallback
            const fb = keywordFallback(text);
            primary = fb.primary;
            confidence = fb.confidence;
        }

        const secondaryTags = extractSecondaryTags(text, primary);
        // Apply India heuristic override as a post-processing step
        const indiaResult = applyIndiaOverride(primary, text, secondaryTags);
        return {
            primary: indiaResult.primary,
            confidence: Math.round(confidence * 1000) / 1000,
            secondaryTags: indiaResult.secondaryTags,
            classificationSignals,
        };
    }

    // ── 2. Sentiment analysis ────────────────────────────────────────────

    analyzeSentiment(text: string): SentimentResult {
        if (!text || text.length < 5) return { sentiment: 'Neutral', score: 0 };

        const words = tokenize(text);
        let pos = 0;
        let neg = 0;
        let negated = false;
        const posFound: string[] = [];
        const negFound: string[] = [];

        for (let i = 0; i < words.length; i++) {
            const w = words[i];
            if (NEGATION_WORDS.has(w)) { negated = true; continue; }
            if (POSITIVE_WORDS.has(w)) {
                negated ? (neg++, negFound.push(`NOT ${w}`)) : (pos++, posFound.push(w));
                negated = false;
            } else if (NEGATIVE_WORDS.has(w)) {
                negated ? (pos++, posFound.push(`NOT ${w}`)) : (neg++, negFound.push(w));
                negated = false;
            } else negated = false;
        }

        const total = pos + neg;
        if (total === 0) return { sentiment: 'Neutral', score: 0, signals: [] };

        const score = (pos - neg) / Math.max(total, 1);
        const normalised = Math.max(-1, Math.min(1, score));

        let sentiment: Sentiment;
        if (normalised > 0.1) sentiment = 'Positive';
        else if (normalised < -0.1) sentiment = 'Negative';
        else sentiment = 'Neutral';

        const signals = [
            ...posFound.slice(0, 3).map(w => `+${w}`),
            ...negFound.slice(0, 3).map(w => `-${w}`),
        ];
        return { sentiment, score: Math.round(normalised * 100) / 100, signals };
    }

    // ── 3. Opinion vs Fact ───────────────────────────────────────────────

    detectOpinionVsFact(title: string, content?: string): OpinionResult {
        const text = [title, content].filter(Boolean).join(' ').toLowerCase();

        let opinionScore = 0;
        let factScore = 0;
        const triggeredOpinionWords: string[] = [];

        // Opinion signals
        for (const word of OPINION_WORDS) {
            if (text.includes(word)) { opinionScore += 1; triggeredOpinionWords.push(word); }
        }

        // Opinion keywords in title (stronger signal)
        const opinionTitlePhrases = ['opinion:', 'op-ed', 'commentary', 'letter to', 'point of view', 'perspective:'];
        for (const p of opinionTitlePhrases) {
            if (title.toLowerCase().includes(p)) { opinionScore += 3; triggeredOpinionWords.push(p); }
        }

        // Factual signals
        for (const pattern of FACTUAL_SIGNALS) {
            if (pattern.test(text)) factScore += 1;
        }

        // Numbers / dates = factual
        const numberCount = (text.match(/\b\d+\b/g) || []).length;
        factScore += Math.min(4, Math.floor(numberCount / 2));

        const total = opinionScore + factScore;
        if (total === 0) return { type: 'Factual', confidence: 0.5, signals: [] };

        const opinionProb = opinionScore / total;
        const signals = triggeredOpinionWords.slice(0, 4);
        if (opinionProb > 0.45) return { type: 'Opinion', confidence: Math.min(0.95, opinionProb + 0.1), signals };
        return { type: 'Factual', confidence: Math.min(0.95, 1 - opinionProb + 0.05), signals: [] };
    }

    // ── 4. Reliability scoring ───────────────────────────────────────────

    scoreReliability(title: string, content?: string, source?: string, pubDate?: string): ReliabilityResult {
        let score = 40; // baseline
        const signals: string[] = [];

        // Source trust bonus
        if (source) {
            const src = source.toLowerCase();
            for (const [key, bonus] of Object.entries(TRUSTED_SOURCES)) {
                if (src.includes(key)) {
                    score += bonus;
                    signals.push(`Trusted source (+${bonus})`);
                    break;
                }
            }
        }

        // Recency score bonus
        if (pubDate) {
            const ts = new Date(pubDate).getTime();
            if (!isNaN(ts)) {
                const hoursAgo = (Date.now() - ts) / (1000 * 60 * 60);
                if (hoursAgo <= 12) {
                    score += 5;
                    signals.push('Highly recent (+5)');
                } else if (hoursAgo <= 24) {
                    score += 2;
                    signals.push('Recent (+2)');
                }
            }
        }

        const text = [title, content].filter(Boolean).join(' ');

        // Clickbait penalty
        let clickbaitPenalty = 0;
        for (const pattern of CLICKBAIT_PATTERNS) {
            if (pattern.test(text)) { clickbaitPenalty += 10; }
        }
        if (clickbaitPenalty > 0) {
            score -= clickbaitPenalty;
            signals.push(`Clickbait signals (-${clickbaitPenalty})`);
        }

        // Factual signals bonus
        let factBonus = 0;
        for (const pattern of FACTUAL_SIGNALS) {
            if (pattern.test(text)) factBonus += 3;
        }
        factBonus = Math.min(15, factBonus);
        if (factBonus > 0) { score += factBonus; signals.push(`Factual content (+${factBonus})`); }

        // Numbers and statistics
        const numCount = (text.match(/\b\d+(\.\d+)?(%|percent|million|billion)?\b/g) || []).length;
        if (numCount >= 3) { score += 5; signals.push('Data/numbers present (+5)'); }

        // Direct quotes
        if (/"[^"]{10,}"/.test(text)) { score += 5; signals.push('Direct quotes (+5)'); }

        // Title length sanity (very short or very long titles are less reliable)
        if (title.length < 20) { score -= 5; signals.push('Very short headline (-5)'); }
        else if (title.length > 120) { score -= 5; signals.push('Overly long headline (-5)'); }

        // ALL-CAPS words in title (sensationalism)
        const capsWords = title.match(/\b[A-Z]{4,}\b/g) || [];
        if (capsWords.length >= 2) { score -= 8; signals.push('Sensationalist caps (-8)'); }

        score = Math.max(0, Math.min(100, Math.round(score)));

        let tier: ReliabilityTier;
        if (score >= 65) tier = 'High';
        else if (score >= 40) tier = 'Medium';
        else tier = 'Low';

        return { score, tier, signals };
    }
}

export const nlpService = new NlpService();
